name: Test
permissions:
  contents: read
on:
  pull_request:

env:
  NODE_VERSION: "24.12"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v4
        name: Checkout

      - uses: zendesk/setup-node@v4
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: zendesk/cache@v4
        name: Cache Node development dependencies
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install Node development dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test
